AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: pdf2txt lambda
Resources:
  pdftotxt:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Description: 'Extract text from PDFs'
      MemorySize: 512
      Timeout: 900
      Environment:
        Variables:
          TARGET_BUCKET: aulendil-glproj2-artifacts
