AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: search function for lab project
Resources:
  searchFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: sample.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 300