AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Search gateway lambda for gl lab
Resources:
  searchGateway:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: search_page.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 300
