AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Upload to search for gl lab
Resources:
  upload2search:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.handler
      Runtime: python3.10
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 900
